### PR TITLE
uart as measured in https://github.com/proddy/EMS-ESP/issues/398#issu…

### PR DESCRIPTION
**Pull request by MichaelDvP**
The  [measurements in #398](https://github.com/proddy/EMS-ESP/issues/398#issuecomment-660003017) uses this uart i posted as zip.
But it's not merged yet, your and bbqkees tests uses a different timing. But this is more like the the timing i see from thermostat RC35 and Mixer MM10.

### CODE REVIEW

**Comment by proddy** [comment]
I'll try this out now, starting with Tx mode 1. Would it help Michael if I hook up my logic analyzer and capture some output so you can compare?

**Comment by MichaelDvP** [comment]
Yes, that would be very helpfull to understand what is the difference. 
I think Bosch is doing some tricks to make their brands incompatible (like the SM200/MS200 on gitter).

**Comment by proddy** [comment]
with tx_mode 1 I'm not getting any tx_fails anymore but MQTT is struggling, perhaps because its interrupted during transmission. Below is after 60mins...

Capture

**Comment by MichaelDvP** [comment]
Maybe this is the double host in the mqtt-subscrptions. 
[see my comment here](https://github.com/proddy/EMS-ESP/issues/421#issuecomment-661675117)
I don't have any mqtt fails, but i'm on esp32 now, trying to analyse the timing. The break-function of  esp32 is very different from esp8266.

**Comment by MichaelDvP** [comment]
Ups, i've merged your latest changes first, but something gone wrong. This should only change the uarts. I'll reopen later.

If you measure with logic analyzer, please also document the telegrams from boiler, thermstate and other devices (if you have).

**Pull request closed without merging**
