### PR TITLE
some enhancements

### PR DESCRIPTION
**Pull request by MichaelDvP**
Ok, here is what i have added and tested on my system (GB125-MC10-RC35-MM10). In the last days i tried to optimize the heating curve, so i need the parameters and the changes from Yves (building, minouttemp) completed the curve-parameters. Check what you find usefull.

- add ntp-server to terminal settings
- add exit-command to terminal
- add heatcurve temperature parameters 'offset' and 'design' to 'thermostat temp' command and mqtt 'thermstat_cmd'
- read EMS long messages with offset (UBAMonitorFast 0x18 and thermostat hc status 0x3D.., needed for RC35 auto-seltemp)
- set thermostat temperatures in advance to get new values by mqtt immediate publishback
- RC35: if not in automode set night/day-temperature by mqtt thermostat_cmd_tempx as it also effects actual settemp
- add logic for signed int8_t values
- merged RC35 addition type 0xA5 from ypaindaveine
- add 'calinttemp' mqtt-command to mqtt 'settings_cmd'
- skip clockoffset and language for RC35 as they are not present in this thermostat
- changed MM50 to EMS+ (see https://github.com/Th3M3/buderus_ems-wiki/blob/master/Quelle_21.md)
- add RC35 thermostat values for damped outdoor temp and internal sensors (sensors commented out, used for testing calibration).
- cases for nested/unnested mixing_data
- add thermostat time to mqtt

### CODE REVIEW

**Comment by proddy** [comment]
wow, lots of changes here! I'll do a review this weekend and see what I'll merge. Thing is, I'm spending all my time on version 2.0 now which has a different back-end architecture so trying to keep 1.9.5 frozen and not making too many updates.

**Comment by MichaelDvP** [comment]
I'll close this pr, it's to much changes for a frozen version. If somebody else requests one of the changes i can do it again.

**Comment by proddy** [comment]
I wanted to port some of the good changes you made over to version 2.0. Is there anything you think its important that I should add now?

**Comment by MichaelDvP** [comment]
Yes, i think the important things are:
- read long telegrams with offset to get actual value of seltemp at pos 37 in telegram 0x3D, 0x47 etc.
- if you change temperatures in mqtt there is a publishback with the old values, that's confusing. Set the values in advance for the publishback. 
- MM50 to EMS+ is a bugfix, hopefully (i have no MM50 and can't test) 
- the RC20 messages from the other PR, as other people, who uses precompiled versions, needs this.

**Comment by MichaelDvP** [comment]
If you like, i can merge these small changes to my RC20 branch, i think than the PR wll be updated.

**Comment by proddy** [comment]
please do, if you don't mind. It'll make it easier for me to also see the changes and port it into version 2.0.

**Comment by proddy** [comment]
Hi @MichaelDvP I went through all your PRs and added some of these additions to version 2.0. I haven't done the Mixing Module yet so only the Thermostat and the main code. What I left out were setting the changes via Telnet or MQTT such as your functions:

ems_setSettingsMinExtTemperature(int16_t mt)
ems_setSettingsClockOffset(int16_t co)
ems_setSettingsDisplay(uint8_t ds)
ems_setSettingsMinExtTemp

as I wasn't sure this is a feature that would be used often? Not sure though since I don't have an RC35.

**Comment by MichaelDvP** [comment]
@proddy I don't think many people use this values. Skip them, you can add later if someone asks for them. These are the values Yves introduced for RC30. 
I used only the MinExtTemperature, as i try to optimize the heating curve. RC35-Thermostat calculates the flow temperature by a parabolic(i think) interpolation between (roomtemp:offsettemp) and (MinExtTemp:designtemp). I changed every value day by day and check flowtemp and roomtemp. But one can set these values manually and they aren't changed often. If the curve fits your house, there is nothing to change.

**Pull request closed without merging**
