### PR TITLE
Brkdetect

### PR DESCRIPTION
**Pull request by susisstrolch**
reworks because of 'tx_mode 2' and protocol issues
    
    ° added markers (GIO12, GPIO14) for logic analyzer debugging
    
    ° change UART initialisation
      - set RxFIFO full to 1 char, so we can detect active telegram on EMS-Bus
      - set RxTOT to 1 char for the same reason
    
    ° in ems_parseTelegram: ignore telegram if  emsRxStatus != EMS_RX_STATUS_IDLE
      because we missed to respond in a timely manner
    
    ° ems_tx_buffer is not void anymore, instead we return the Tx status
    ° extended the emsTxStatus
      - EMS_TX_WTD_TIMEOUT: timeout while waiting for echo of last Tx byte
        out telegram was ignored by the bus master, so the byte wasn't echoed
      - EMS_TX_BRK_DETECT:  BRK detected while sending the telegram
        bus master send us a break because of protocol violation
    
    ° add burnStarts, burnWorkMin and heatWorkMin to MQTT boiler message
    
    TODO:
      + take care of ems_tx_buffer return code
      + accept direct telegram in ems_parse_telegram and do a proper acknowledge
      + split the heartbeat in static (version, IP-address) and dynamic (RSS etc)
      + change the hearbeat to a JSON structure so we can easier pick the uptime

### CODE REVIEW

**Comment by susisstrolch** [comment]
Jep - it‘s only 3 char times down during the boot, so no disturb any more. 

Sent by mobile device

**Comment by proddy** [comment]
Hi Juergen, so merged into 1.8.1 beta 21 and noticed
 - I see a few 'corrupt' messages. For example after a 'refresh' command which does a sequence of Tx calls there are always 1-2 that fail. At least on my system. I didn't have this problem with the previous implementation of tx_mode=2
- Still getting WDT. System reboots between 10-15 minutes. Haven't had time to trace root cause yet.

**Comment by susisstrolch** [comment]
- corrupt telegram 
Clearly the issue I mentioned in #151, issue 1)

- reboot
I saw a load/store exception. I‘ll try to investigate using This https://medium.com/diy-my-smart-home/esp-tipp-platformio-und-exceptions-7a77f232ed50 approach...

Von meinem iPad gesendet

**Comment by susisstrolch** [comment]
The reboot is because out of heap error. 
We should really care about ems_tx_buffer error return. 

Von meinem iPad gesendet

**Pull request merged**
