### PR TITLE
Uart mode 5

### PR DESCRIPTION
**Pull request by MichaelDvP**
Can you test this tx_mode 5 on your system, it's same readback-logic as mode 1 but working with the rx-interrupt. Debug logging while sending result in the same issues as the timer-modes, seems the logger blocks all interrupts for some ms. 

Another change: there is alway a bit confusion with the short/ushort notsets, some values 0x7D00, some 0x0800, some 0x8300.

### CODE REVIEW

**Comment by proddy** [comment]
I'll test later. I've made some big changes to telegram.cpp on how it handles retries and want to get the working 100% first

**Comment by proddy** [comment]
with tx_mode 5 I get a 50% pass rate.

Capture

**Comment by MichaelDvP** [comment]
Sad that this is also not working. Echo time is a bitshorter than mode 1, isn't it?

There is a issue in retry, put the `return`  from line 644 after line 636. 
Why does "send message data:" give a wrong output? I can't figure out. Also the "received" seems not correct?

**Comment by proddy** [comment]
thanks for pointing out the retry() bug. Just pushed a new change.

the "send message data:" is because now when doing a Tx I save the actual Telegram object and not the complete telegram's raw data. So when displaying the last sent Tx I can't show all the raw bytes, only the data structure like telegram->src, telegram->type_id etc. But I could create a function to re-construct an EMS telegram as bytes from a 'Telegram' object but at the time I didn't think it would be worthwhile since it's only showed once for debugging. Its only a few mins to write the code so if you think it makes sense I'll add it, no problem.

**Pull request merged**
