### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lobocobra**
Hi Proddy

Many thanks for implementing my code. I learned alot by looking at your changes.
=> As some of the features did not work, I fixed them and this PR represents a working code, based on your changes.

### CODE REVIEW

**Comment by proddy** [comment]
it's really hard to see the differences between the current dev branch and your PRs so I tried to add them manually.

**Comment by lobocobra** [comment]
Sorry to hear, I tried to put //lobocobra, everywhere I changed some code.
=> let me test your latest version, in case I have some issues after I will find out, where are the differences

**Comment by lobocobra** [comment]
Cool, now all except one tiny thing is working! Many thanks for that.


**Last gap**
`Thermostat stats:
  Thermostat type: RC35 (ProductID:86 Version:21.04)
  Setpoint room temperature: ? C
  Current room temperature: ? C
  Day temperature: 22.5 C
  Night temperature: 19.0 C
  Vacation temperature: 16.0 C
  Thermostat time is 20:10:33 7/4/2019
  Mode is set to auto`

When you have a floor-heating then you will use the external temp and the "Current room temp sensor" is deactivated. 
The firmware stops execution if one of both values are not valid, this leads to 2x "?"

To fix this quickly (accepting the second value to be at 0)
ems-esp.cpp line 623....
Original code:
        if ((EMS_Thermostat.curr_roomTemp <= 0) || (EMS_Thermostat.setpoint_roomTemp <= 0))
Needed change:
        if ((EMS_Thermostat.curr_roomTemp <= 0) && (EMS_Thermostat.setpoint_roomTemp <= 0))

But honestly this is even less than a minor issue! nobody is in the console the whole day long :)

**Comment by lobocobra** [comment]
I close the PR as your inserted code fixes all remaining issues.
=> Many thanks for the effort you invested to integrate my code!

**Comment by proddy** [comment]
no, thank you! You've been an enormous help and all your testing, patience and contributions keep this project alive.

**Pull request closed without merging**
