### PR TITLE
Dallas Parasitic mode fix

### PR DESCRIPTION
**Pull request by JewelZB**
Bulding onto the previous fix of MichaelDvP and the 1.9.5 ds18.cpp I have done some testing and this seems to fix the Dallas parasitic mode. The sensors now appear in the webgui and MQTT.
(fix proddy#490)

### CODE REVIEW

**Comment by MichaelDvP** [comment]
Oh, i missed to see the depowers, thank you for the correction. 
But i have 2 remarks/questions. 
- Are you sure about line 67 in `sensors.cpp`? If you don't check the presence-pulse there will always be a sensor configured, but giving a read error. 
- in syslog you skip the complete reinitialisation if loglevel is off, but then there is no change until next reboot. Isn't it better only to disable the mark, or mark and server? i.e. to do the check like this:
```
    if (syslog_level_ == uuid::log::OFF) {
        syslog_.mark_interval(0);
        syslog_.destination(0);
    } else {
        syslog_.mark_interval(syslog_mark_interval_);
        syslog_.destination(addr);
    }
```

**Comment by proddy** [comment]
I think the correct way is to have a SysLog enabled/disabled option, just like with the other features such as MQTT and NTP. Having Syslog enabled, with level OFF and a Mark supports the underlying protocol and behaviour of the service.

@MichaelDvP shall I add this or do you want to?

**Comment by JewelZB** [comment]
> * Are you sure about line 67 in `sensors.cpp`? If you don't check the presence-pulse there will always be a sensor configured, but giving a read error.

No, not sure, the datasheet states this also. The ds18.cpp also issues a reset, but without checking the return value. I tested it out and would always get a "bus reset error" when on parasitic, even when the two connected sensors report their temperatures without problems when the presence pulse is ignored.

Also the INPUT_PULLUP on the data pin before the bus is searched is a bit tricky, but again, without it - no devices. Of course the devices are connected using the pullup resistor to begin with as per the datasheet.

Could be the capacitance on the 2 meters of wiring on the sensors. Dont know. But then, parasitic mode is sensitive anyway. :)

**Comment by MichaelDvP** [comment]
@JewelZB Do you mean the (normally commented out) "Bus reset failed" in line 74? If you disconnect the sensors, does it give you error messages or only "No sensors found"? I have no sensor to check, but think: if it works correctly, it's right.
@proddy I think better you do the syslog settings, i'm not familiar with the syslog standard.

**Comment by MichaelDvP** [comment]
@proddy regarding syslog: Isn't the hostsetting the right criteria? If no host -> no syslog, otherwise level and mark are displayed and can be set independently.

**Comment by proddy** [comment]
For syslog I'll create a new Enhancement issue. It should really be it's own service in the web ui next to NTP and MQTT, and behave the same. Also remove OFF as a level option.

**Comment by JewelZB** [comment]
> @JewelZB Do you mean the (normally commented out) "Bus reset failed" in line 74? If you disconnect the sensors, does it give you error messages or only "No sensors found"? I have no sensor to check, but think: if it works correctly, it's right.

I mean the normally commented out "bus reset failed" message. I uncommented it, and got that message. If it does that, it nevers continues to READING and so SCANNING state. Thus, no sensors found is the endresult.

**Comment by MichaelDvP** [comment]
I tested with my 7 sensors, all non-parasite-versions, but with activated parasite mode.
Connecting, disconnecting, all works well with `if (bus_.reset() || parasite_)`.

**Comment by MichaelDvP** [comment]
I've merged the dallas changes and changes the settings page to always show the syslog settings

**Pull request closed without merging**
